#ifndef PROTOCOLDEFINITIONS_H
#define PROTOCOLDEFINITIONS_H

#define SIZE_OF_PROTOCOL_CODE_IN_STRING 3
#define SIZE_OF_DELIMITER 1
#define SIZE_OF_END_STRING 1
#define PLACE_OF_DELIMITER_AFTER_PROTOCOL_CODE 3

#define START_CONNECTION 101
#define CONNECTION_STARTED 102
#define CONNECTION_FAILED 103
#define TOKEN_NOT_VALID 104

#define REGISTER_USER 201
#define REGISTER_FAILED_EMAIL_NOT_LEGAL 202
#define REGISTER_FAILED_EMAIL_IN_USE 203
#define REGISTER_FAILED_PASSWORD_NOT_LEGAL 204
#define REGISTER_FAILED 205
#define REGISTER_SUCCESSFULLY 206

#define LOGIN_USER 211
#define LOGIN_FAILED_EMAIL_NOT_LEGAL 212
#define LOGIN_FAILED_USER_NOT_REGISTERED 213
#define LOGIN_FAILED_WRONG_CREDENTIALS 214
#define LOGIN_USER_SUCCESSFULLY 215

#define LOGOUT_USER 220
#define LOGOUT_USER_SECCESSFULLY 221
#define LOGOUT_USER_FAILED 222

#define CHANGE_DIRECTORY 301
#define CHANGE_DIRECTORY_FAILED_NOT_VALID_DIRECTORY 302
#define CHANGE_DIRECTORY_FAILED 303
#define CHANGE_DIRECTORY_SUCCESSFULLY 304
#define GET_DIRECTORY_FAILED 305

#define UPLOAD_ALL_FILES 401
#define UPLOAD_ALL_FILES_START 402
#define UPLOAD_FILE 403
#define UPLOAD_DIRECTORY 404
#define START_UPLOAD_FILE 409
#define CAN_START_UPLOAD_OF_FILE 405
#define GOT_FILE_SUCCESSFULLY 406
#define MKDIR_SUCCESSFULLY 407
#define FILE_UPLOAD_FAILED 408

#define FAILED_TO_CREATE_FILE_ON_SERVER 412
#define UPLOAD_ALL_FILES_FAILED_STORE_FILE 411
#define MKDIR_FAILED 413

#define SET_AUTO_SYNC 501
#define SET_AUTO_SYNC_SUCCESSFULLY 502
#define SET_AUTO_SYNC_FAILED 503
#define STOP_AUTO_SYNC 510
#define STOP_AUTO_SYNC_FAILED 511
#define STOP_AUTO_SYNC_SUCCESSFULLY 512 

#define SHARE_FILE 601
#define FILE_NOT_EXIST 602
#define FILE_SHARE_SUCCESSFULLY 603
#define FILE_SHARE_FAILDED 604
#define GET_SHARED_FILES 605
#define NO_SHARED_FILES 606
#define FOUND_SHARED_FILES 607
#define FINISHED_SHARED_FILES_DOWNLOAD 608

#endif